'use strict';

/**
 * gateway-patch.js — Security & Production Fixes for DOZ UP Gateway
 * ==================================================================
 * Applies all new security middleware to the Express app without
 * requiring a rewrite of the 15,000-line gateway.js.
 *
 * Usage — add ONE line near the top of gateway.js, after `const app = express()`:
 *
 *   const { centralErrorHandler } = require('./src/gateway-patch')(app);
 *   // ... all your routes ...
 *   app.use(centralErrorHandler); // must remain LAST
 *
 * What this module does:
 *   1. Security headers  — Helmet + CSP via security-headers.js
 *   2. HTTP logging      — structured pino request/response logger
 *   3. CSRF cookie       — double-submit cookie seeding (stateless)
 *   4. CSRF enforcement  — rejects mutating requests without a matching header
 *   5. Secure cookies    — overrides res.cookie to apply httpOnly/secure/sameSite
 *      (does NOT touch CSRF token cookie — that one intentionally sets httpOnly:false)
 *   6. Admin route guard — catch-all 401 for /api/admin/* missing a Bearer token
 *   7. Permissions policy header — camera/mic/geo/usb disabled
 *   8. app.locals        — exposes patched middleware for inline use in routes
 *
 * Returns `{ centralErrorHandler }` so gateway.js can register the error handler
 * after all routes are defined.
 */

// ─── Middleware imports ────────────────────────────────────────────────────────────────────────────
const { securityHeaders, permissionsPolicy } = require('./middleware/security-headers');
const { csrfCookieMiddleware, csrfProtection } = require('./middleware/csrf');
const { requireAuth, requireAdmin, optionalAuth } = require('./middleware/auth');
const { centralErrorHandler, asyncWrap } = require('./middleware/async-wrap');
const { setSecureCookie, clearSecureCookie, SESSION_COOKIE_OPTIONS } = require('./middleware/cookie-config');
const { screenshotUpload, syncUpload, uploadRateLimiter } = require('./middleware/upload-limiter');
const { logger, httpLogger } = require('./utils/logger');
const config = require('./config');

// ─── Admin paths that are reachable without a session token ───────────────────────────────────────
const PUBLIC_ADMIN_PATHS = [
    '/api/admin/auth/login',
    '/api/admin/auth/verify',
];

// ─── Paths where CSRF should never be enforced ────────────────────────────────────────────────────
const CSRF_SKIP_PREFIXES = [
    '/api/webhook',
    '/stripe/webhook',
    '/webhook',
];

// ─── HTTP methods that do NOT mutate state ───────────────────────────────────────────────────────────
const SAFE_METHODS = new Set(['GET', 'HEAD', 'OPTIONS']);

// ─── Helpers ────────────────────────────────────────────────────────────────────────────────────

/**
 * Returns true if the request path begins with any of the given prefixes.
 * @param {string} reqPath
 * @param {string[]} prefixes
 * @returns {boolean}
 */
function startsWithAny(reqPath, prefixes) {
    return prefixes.some((prefix) => reqPath === prefix || reqPath.startsWith(prefix + '/'));
}

// ─── Main export ────────────────────────────────────────────────────────────────────────────────

/**
 * Applies all security patches to the Express app.
 *
 * @param {import('express').Application} app
 * @returns {{ centralErrorHandler: Function }}
 */
module.exports = function applySecurityPatches(app) {

    // ── Guard: only accept a real Express app ─────────────────────────────────────────────
    if (!app || typeof app.use !== 'function') {
        throw new TypeError('[gateway-patch] applySecurityPatches() requires an Express app instance.');
    }

    logger.info('[gateway-patch] Applying security patches...');

    // ── 1. Security headers (Helmet + CSP) ──────────────────────────────────────────────
    //    Applied before everything else so every response carries these headers,
    //    including error responses generated by later middleware.
    //    Skipped for share.doz.com / rdp.doz.com / ai.doz.com — those subdomains
    //    have their own rules (mirrors gateway.js:204-215).
    app.use((req, res, next) => {
        const host = req.headers.host || '';
        if (
            host.includes('share.doz.com') ||
            host.includes('rdp.doz.com') ||
            host.includes('ai.doz.com')
        ) {
            return next();
        }
        return securityHeaders()(req, res, next);
    });

    // ── 2. Permissions-Policy ───────────────────────────────────────────────────────────────
    app.use(permissionsPolicy);

    // ── 3. HTTP request / response logging ──────────────────────────────────────────────────
    //    Uses pino via httpLogger — redacts Authorization, Cookie, JWT, Stripe keys.
    app.use(httpLogger);

    // ── 4. CSRF cookie seeding ──────────────────────────────────────────────────────────────
    //    Sets the csrf_token cookie (httpOnly:false — JS must be able to read it).
    //    Requires cookie-parser to already be registered in gateway.js.
    //    If cookies are not yet parsed, csrfCookieMiddleware silently skips token
    //    reuse and issues a fresh token — this is safe for double-submit.
    app.use(csrfCookieMiddleware);

    // ── 5. CSRF enforcement on state-changing routes ────────────────────────────────────────
    //    Rejects POST/PUT/PATCH/DELETE that lack a matching x-csrf-token header.
    //    Webhooks are excluded because they use their own signature verification.
    //    Requests carrying x-api-key are also excluded (server-to-server calls).
    app.use((req, res, next) => {
        if (SAFE_METHODS.has(req.method)) return next();
        if (startsWithAny(req.path, CSRF_SKIP_PREFIXES)) return next();
        return csrfProtection(req, res, next);
    });

    // ── 6. Secure cookie override ────────────────────────────────────────────────────────────
    //    Wraps res.cookie so every downstream call automatically inherits
    //    httpOnly, secure (production-only), and sameSite:lax unless the caller
    //    explicitly overrides those fields.
    //
    //    The CSRF cookie (set in step 4) is excluded because its httpOnly MUST
    //    remain false — JavaScript needs to read it to build the x-csrf-token header.
    app.use((req, res, next) => {
        const originalCookie = res.cookie.bind(res);
        res.cookie = function patchedCookie(name, value, options = {}) {
            // Never harden the CSRF cookie — its httpOnly:false is intentional.
            if (name === 'csrf_token') {
                return originalCookie(name, value, options);
            }
            const secureOpts = {
                httpOnly: true,
                secure:   config.env.NODE_ENV === 'production',
                sameSite: 'lax',
                ...options,           // caller overrides are still respected
            };
            return originalCookie(name, value, secureOpts);
        };
        next();
    });

    // ── 7. Admin route catch-all guard ────────────────────────────────────────────────────────
    //    Any /api/admin/* request that reaches this middleware without a Bearer
    //    token is rejected with 401.  Routes that already use requireAdmin()
    //    will perform the full token validation (device binding, permissions).
    //    This catch-all protects the ~99 admin routes that lack explicit auth.
    //
    //    Public admin endpoints (login, verify) are explicitly whitelisted.
    app.use('/api/admin', (req, res, next) => {
        // Allow safe methods through — e.g. admin health check GET endpoints.
        if (SAFE_METHODS.has(req.method)) return next();

        const isPublic = PUBLIC_ADMIN_PATHS.some(
            (p) => req.path === p || req.originalUrl.split('?')[0] === p
        );
        if (isPublic) return next();

        const authHeader = req.headers.authorization;
        if (!authHeader || !authHeader.startsWith('Bearer ')) {
            return res.status(401).json({
                error: 'Authentication required',
                code:  'TOKEN_MISSING',
            });
        }

        // Token format looks correct — let the route's own requireAdmin() validate it.
        next();
    });

    // ── 8. Expose utilities on app.locals ─────────────────────────────────────────────────────
    //    Route handlers can reference these without importing them individually:
    //      const { requireAuth, asyncWrap } = req.app.locals;
    app.locals.requireAuth         = requireAuth;
    app.locals.requireAdmin        = requireAdmin;
    app.locals.optionalAuth        = optionalAuth;
    app.locals.asyncWrap           = asyncWrap;
    app.locals.screenshotUpload    = screenshotUpload;
    app.locals.syncUpload          = syncUpload;
    app.locals.uploadRateLimiter   = uploadRateLimiter;
    app.locals.setSecureCookie     = setSecureCookie;
    app.locals.clearSecureCookie   = clearSecureCookie;
    app.locals.SESSION_COOKIE_OPTIONS = SESSION_COOKIE_OPTIONS;
    app.locals.logger              = logger;

    logger.info('[gateway-patch] Security patches applied successfully.');

    // ── 9. Return centralErrorHandler ───────────────────────────────────────────────────────────
    //    gateway.js MUST register this AFTER all routes:
    //      const { centralErrorHandler } = require('./src/gateway-patch')(app);
    //      // ... routes ...
    //      app.use(centralErrorHandler);
    return { centralErrorHandler };
};
